### ISSUE TITLE
Do I need this gem to be enabled if I am running my app under Linux?

### ISSUE THREAD

**Issue by acrolink** [tzinfo/tzinfo-data#13]
Thank you.

**Comment by philr** [comment]
No, the tzinfo-data gem is not needed on Linux.

TZInfo can read the system zoneinfo time zone files included in most Linux distributions and can therefore be used without the tzinfo-data gem.

You may still prefer to use tzinfo-data on Linux if:

1. Your application needs to precisely control the version of the IANA time zone database being used.
2. Your application cares about the difference between time zones defined by a set of transition times and those defined as links to or aliases of other time zones. Information about links/aliases is not available in the system zoneinfo files, but is included in tzinfo-data.
3. The accuracy of [`TimezonePeriod#std_offset`](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#std_offset-instance_method) (the amount of time the clock is advanced in periods where daylight savings time is observed) is critical to your application. This information is not available in the system zoneinfo files, so has to be estimated by observing clock changes during transitions. The tzinfo-data gem includes the precise `std_offset` values. Note that [`TimezonePeriod#utc_total_offset`](http://www.rubydoc.info/gems/tzinfo/TZInfo/TimezonePeriod#utc_total_offset-instance_method) will always be correct with both zoneinfo files and the tzinfo-data gem.
