### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aldrinmartoq** [tzinfo/tzinfo-data#16]
Hi @philr, just wanted to thank you for this package, couldn't find you on twitter.

I'm trying to resolve the problem when a new version of tzdata is released, so I made a couple of things:
1. a [ruby package](https://github.com/a0/a0-tzmigration-ruby) that contains each version of the database in [JSON files](https://a0.github.io/a0-tzmigration-ruby/data/), and can return the diff (for ex: what do I have to check in my system if I'm in 2016c and install 2017a, for America/Santiago and America/Punta_Arenas). I extracted all the data from your tzinfo-data gem.
2. a [npm package](https://github.com/a0/a0-tzmigration-js) that uses the json data generated above, and do the same in javascript.
3. a [demo](https://a0.github.io/a0-tzmigration/) to see the changes, for example: [here you can see the changes above for America/Santiago → America/Punta_Arenas](https://a0.github.io/a0-tzmigration/demo/?ta=America%2FSantiago&va=2016c&tb=America%2FPunta_Arenas&vb=2017a).

I will post a medium post later on the topic, but thanks again for your work.

**Comment by philr** [comment]
Thanks for letting me know about your new project. It looks interesting. I've written scripts before to compare the offsets of used time zones between different tzinfo-data versions, but this is much more comprehensive.

I've had a quick look at your `DataGenerator` code. I note that it is currently [accessing the protected `#info` method](https://github.com/a0/a0-tzmigration-ruby/blob/9a8b97903742d8dbf85c7272e1cfc8b900756784/lib/a0/tzmigration/data_generator/process.rb#L86) to obtain transition data. Is there a reason why you're not using the public [`TZInfo::Timezone#transitions_up_to`](https://www.rubydoc.info/gems/tzinfo/1.2.5/TZInfo%2FTimezone:transitions_up_to) method instead?

**Comment by aldrinmartoq** [comment]
Oh no, you got me doing something inappropriate ;-)

Sorry, I use the protected methods because wanted the full list of transitions, and didn't want a hardcoded end date.

By the way, the [moving 50 year limit](https://github.com/tzinfo/tzinfo-data/blob/master/lib/tzinfo/data/tzdataparser.rb#L100) is kind of an issue for me now, the utilities reports changes between versions when nothing changed from the tzdb perspective, like [this one](https://a0.github.io/a0-tzmigration/demo/?ta=Africa%2FCasablanca&va=2017c&tb=Africa%2FCasablanca&vb=2018a&m=table).

I'm still working on documentation, I think it looks [good enough so far](https://a0.github.io/a0-tzmigration/).
