### ISSUE TITLE
Supporting SystemV time zones

### ISSUE THREAD

**Issue by nasa42** [tzinfo/tzinfo-data#18]
I noticed that [systemv](https://data.iana.org/time-zones/tzdb-2018g/systemv) time-zones are not included. We need to support some machines that still use these deprecated time-zones and I was wondering what's the rationale behind not including them and if it would be possible to add support for them in tzinfo-data.

**Comment by philr** [comment]
The SystemV zones are not included in the official Time Zone Database distribution. The Zone directives that would define these zones in the [systemv file](https://data.iana.org/time-zones/tzdb-2018g/systemv) you link to are commented out. This means that they are ignored by both the Time Zone Database `zic` tool and by the tzinfo-data `build_tz_modules` Rake task.

The policy I've been applying and intend to continue with is to have tzinfo-data bundle the Time Zone Database (in Ruby-form) exactly as it is distributed. I'm leaving all decisions about what does or does not constitute a valid time zone to the Time Zone Database maintainers.

If you want to rebuild tzinfo-data and add the SystemV zones yourself, you can do the following:

1. Checkout the tzinfo-data git repository and change to the tzinfo-data directory.
2. Run `bundle exec rake tzdb:extract:data` to download and extract the tzdata tarball.
3. Remove the `## ` prefix from all lines starting `## Zone` in the `tzdb/$version/data/systemv` file (replace `$version` with the current version being built, as specified in `lib/tzinfo/data/version.rb`).
4. Run `bundle exec rake build_tz_modules` to rebuild the time zone modules.
5. Optionally run `bundle exec rake test` to compare the built modules with the result of running `zdump` on the equivalent zoneinfo files.

It should also be noted that the SystemV zones are not very helpful. The time zones that attempt to apply daylight savings time, such as SystemV/EST5EDT, are not aware of changes made to DST rules in the US after 1976. Other zones, such as EST5, don't apply DST rules at all.

**Comment by nasa42** [comment]
Is there any authoritative source of mapping between SystemV time zones and modern time zones? I understand that a correct mapping is unlikely because of DST issues mentioned above, but if I can find any reference to what regions they represented, I can map them to the modern time zone of their region.

**Comment by nasa42** [comment]
Thank you so much! This is very helpful! We'll use the [Debian mappings](https://sources.debian.org/src/tzdata/2018i-1/debian/patches/systemv.diff/) to support these systems.

> If you're aiming for compatibility with another system, it'd probably be best to check what that system is doing (e.g. by checking what transitions are returned by zdump).

Unfortunately, we do not have control over these remote systems. They just report to us with their system time zone.
