### ISSUE TITLE
GitHub Pages website out of date

### ISSUE THREAD

**Issue by olleolleolle** [tzinfo/tzinfo-data#19]
Hi!

I took a look at the gemspec, and saw the homepage specification attribute was using "http", so I visited it, and saw that it supported "https". Was about to update the attribute, but saw the gem version badge presented by GemFury there.

- On the repo's rendered README, it's the current one, 1.2 something
- On the homepage in GitHub Pages, it's 2.0.1 - misleading

The homepage information could perhaps be turned into information in the README, if the website is not to maintained (there's no specific Git branch for the website, which is common with GitHub Pages websites).

Do you want to keep the homepage around?

**Comment by philr** [comment]
The web page is for both the tzinfo and tzinfo-data gems (tzinfo-data is only intended for use as an add-on to tzinfo). The current version of tzinfo is 2.0.1. The current version of tzinfo-data is 1.2019.3.

The source for the web site can be found in the [tzinfo.github.io repository](https://github.com/tzinfo/tzinfo.github.io).

I've [modified](https://github.com/tzinfo/tzinfo.github.io/commit/067c7504d2c0ba6b40a96e3faed9d81451ea41a0) the web site to add separate version numbers for the tzinfo and tzinfo-data gems.

I've also [changed](https://github.com/tzinfo/tzinfo-data/commit/c2f2ebedc442ec64a3a3e54725918264f8a5e019#diff-9a35156209cc1e4d8b4498aa38cd11c4) the tzinfo-data gemspec to use https for the homepage.

**Comment by olleolleolle** [comment]
Fantastic!
