### ISSUE TITLE
Kazakhstan TZ change

### ISSUE THREAD

**Issue by damiann** [tzinfo/tzinfo-data#24]
The [Feb 2024a release notes](https://mm.icann.org/pipermail/tz-announce/2024-February/000081.html) mentions:

> Kazakhstan unifies on UTC+5.  This affects Asia/Almaty and Asia/Qostanay which together represent the eastern portion of the country that will transition from UTC+6 on 2024-03-01 at 00:00 to join the western portion.

When is the data expected to be updated/released with this change?

**Comment by philr** [comment]
The changes from 2024a were included in tzinfo-data [v1.2024.1](https://github.com/tzinfo/tzinfo-data/releases/tag/v1.2024.1) (released on 1 February). There will be a tzinfo-data release for each IANA Time Zone Database release, usually within a day or two.

The old tzinfo 0.3 branch has also [been updated](https://github.com/tzinfo/tzinfo/commit/6a739f42ecb3247aa4f1abae7ddd9cfdbee31c00) with the 2024a changes. TZInfo 0.3.x isn't really supported any longer with only occasional releases. You can obtain the latest 0.3.x code and data by loading the tzinfo gem from git in your `Gemfile`:

```ruby
gem 'tzinfo', git: 'https://github.com/tzinfo/tzinfo.git', branch: '0.3'
```

**Comment by damiann** [comment]
@philr sorry, could you clarify a bit. We're currently using `tzinfo (2.0.5)` and `tzinfo-data (1.2024.1)`(latest) and we will need to downgrade to `0.3` in order to use the latest data? Bumping `tzinfo-data` independently doesn't mean we get the latest IANA updates, we still have to wait for them to be update in the `tzinfo` gem?

**Comment by philr** [comment]
You don't need to downgrade.

You have the latest data tzinfo v2.0.5 and tzinfo-data v1.2024.1.

**Comment by philr** [comment]
Prior to tzinfo v1.0.0, the data used to be bundled with tzinfo. Version 1.0.0 and onwards will obtain data from either tzinfo-data or the system zoneinfo files.

**Comment by damiann** [comment]
Got it! So the offset I'm seeing for Astana, Kazakhstan looks like it's still showing GMT+6 instead of the new GMT+5. So something is off. 

```ruby
pry(main)> TZInfo::Data::Version::TZDATA
=> "2024a"
pry(main)> ActiveSupport::TimeZone['Astana']
=> #<ActiveSupport::TimeZone:0x0000ffff69fd5f70 @name="Astana", @tzinfo=#<TZInfo::DataTimezone: Asia/Dhaka>, @utc_offset=nil>
pry(main)> ActiveSupport::TimeZone['Astana'].now.utc_offset
=> 21600
pry(main)> ActiveSupport::TimeZone['Astana'].tzinfo.identifier
=> "Asia/Dhaka"
```

**Comment by philr** [comment]
```ruby
=> #<ActiveSupport::TimeZone:0x0000ffff69fd5f70 @name="Astana", @tzinfo=#<TZInfo::DataTimezone: Asia/Dhaka>, @utc_offset=nil>
```

ActiveSupport's Astana time zone is [mapped to Asia/Dhaka](https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/activesupport/lib/active_support/values/time_zone.rb#L137) (Bangladesh). That seems to be incorrect (and that time zone didn't change in 2024a).

Asia/Almaty and Asia/Qostanay are the Kazakhstan time zones that have changed. With the previous v1.2023.4 tzinfo-data release (2023d), Asia/Almaty is on UTC+6 prior to and after 1 March 2024:

```ruby
TZInfo::DataSource.get
#=> #<TZInfo::DataSources::RubyDataSource: tzdb v2023d, tzinfo-data v1.2023.4>
tz = TZInfo::Timezone.get('Asia/Almaty')
#=> #<TZInfo::DataTimezone: Asia/Almaty>
tz.to_local(Time.utc(2024,2,29,12,0,0))
#=> 2024-02-29 18:00:00 +0600
tz.to_local(Time.utc(2024,3,1,12,0,0))
#=> 2024-03-01 18:00:00 +0600
```

With v1.2024.1 (2024a), Asia/Almaty switches from UTC+6 to UTC+5:

```ruby
TZInfo::DataSource.get
#=> #<TZInfo::DataSources::RubyDataSource: tzdb v2024a, tzinfo-data v1.2024.1>
tz = TZInfo::Timezone.get('Asia/Almaty')
#=> #<TZInfo::DataTimezone: Asia/Almaty>
tz.to_local(Time.utc(2024,2,29,12,0,0))
#=> 2024-02-29 18:00:00 +0600
tz.to_local(Time.utc(2024,3,1,12,0,0))
#=> 2024-03-01 17:00:00 +0500
```

The [commentary in the Time Zone Database](https://github.com/eggert/tz/blob/380c07cef01c71c1f93e9709d9f8c79b91cff063/asia#L2473-L2478) states that Asia/Almaty is for most locations in Kazakhstan including the Akmola region containing/surrounding Astana. I think ActiveSupport's Astana time zone should therefore actually be mapped to Asia/Almaty. You'll need to raise an issue on the [rails/rails](https://github.com/rails/rails) project.

**Comment by damiann** [comment]
Thank you!
