### ISSUE TITLE
No source of timezone data could be found. (TZInfo::DataSourceNotFound)

### ISSUE THREAD

**Issue by hostingnuggets** [tzinfo/tzinfo-data#8]
With RailsInstaller 3.1.0 (Ruby 2.1) on Windows 2008 Server (32bit) I can't start my rails server because of the following error:

```D:/RailsInstaller/Ruby2.1.0/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)```

In my Gemfile I am using the following entry for tzinfo-data:

```gem 'tzinfo-data', '= 1.2016.1', platforms: [:x64_mingw, :mingw, :mswin], path: 'C:\Temp'```

Note here that my server does not have any connection to outside that's why I specified the path in the Gemfile, where I have downloaded and stored the following gem: tzinfo-data-1.2016.1.gem

**Comment by philr** [comment]
The error means that TZInfo cannot locate `tzinfo/data` on the Ruby load path (or find a zoneinfo directory). Further information about the error can be found at http://tzinfo.github.io/datasourcenotfound.

Have you unpacked the tzinfo-data gem? The `path` option is supposed to reference the unpacked location for the gem (see http://bundler.io/v1.11/gemfile.html). It sounds like you are saying that you have just downloaded tzinfo-data-1.2016.1.gem and saved it to C:\Temp (which won't work).

You could run:

    gem install C:\Temp\tzinfo-data-1.2016.1.gem

to install from the downloaded gem file and then remove the `path` option from your Gemfile.

Alternatively, you could unpack the gem by running

    gem unpack --target C:\Temp C:\Temp\tzinfo-data-1.2016.1.gem

and then change the `path` option in your Gemfile to `C:\Temp\tzinfo-data-1.2016.1`.

**Comment by hostingnuggets** [comment]
@philr Thanks for the pointers, I have installed the gem as you recommended at it is located in `D:\RailsInstaller\Ruby2.1.0\lib\ruby\gems\2.1.0\gems\tzinfo-data-1.2016.1\lib\tzinfo\data` but still I get the same error message when I start the rails server. 

How can I specify the tzinfo/data load path in Ruby? And in which config file would that be?

**Comment by philr** [comment]
Have you run [`bundle update`](http://bundler.io/bundle_update.html) since installing the tzinfo-data gem and modifying your Gemfile? If you don't have access to the Internet, then you'll need to either run `bundle update --local` or run `bundle update` on a different machine and then transfer the Gemfile.lock file across.

Bundler will take care of adding the gems you specify to the Ruby load path.

You might like to look at the section on [Deploying Your Application](http://bundler.io/deploying.html#deploying-your-application) in the Bundler documentation, which covers a process for deploying to a machine that doesn't have Internet access.

**Comment by hostingnuggets** [comment]
Thanks the `bundle update --local` did the trick and it now works.

**Comment by GeoffreyDechambre** [comment]
Hello,

i have the error : 
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/tzinfo-1.2.3/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)

But i did all the trick below and nothings change.

I'm on windows (ruby 2.3.3 rails 4.2.6)
i have in my gemfile the link to tzinfo-data
i try to reinstal, bundle update etc, but i'm always facing the same issue. 

Could you help me please ?

Best regards

**Comment by philr** [comment]
@GeoffreyDechambre On Windows, the error means that `require 'tzinfo/data'` is failing. For some reason the tzinfo-data gem is not being made available when Rails is running.

To help work out what's going wrong, please post the output of running `bundle update` as well as the contents of your `Gemfile` and `Gemfile.lock` files.
